name: mint_dentistry
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  go_router: ^10.1.2
  carousel_slider: ^4.2.1
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/carousel/Onboarding1.png
    - assets/images/carousel/Onboarding2.png
    - assets/images/carousel/Onboarding3.png

  fonts:
    - family: Didot
      fonts:
        - asset: assets/fonts/Didot-Regular.ttf
        - asset: assets/fonts/Didot-Italic.ttf
          weight: 900
        - asset: assets/fonts/Didot-Italic.ttf
          style: italic
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue-Regular.ttf
        - asset: assets/fonts/HelveticaNeue-Bold.ttf
          weight: 900
        - asset: assets/fonts/HelveticaNeue-Italic.ttf
          style: italic
        - asset: assets/fonts/HelveticaNeue-Light.ttf
          weight: 300
        - asset: assets/fonts/HelveticaNeue-Medium.ttf
          weight: 500
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
